In [1]:
import tensorflow as tf

C:\Users\shrisha.bharadwaj\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a = tf.constant(3, shape = (3,4), name = "array_1")
b = tf.constant(5, shape = (3,4), name = "array_2")
addition = tf.add(a,b, name= "Op1")
writer = tf.summary.FileWriter("./Graph", tf.get_default_graph())
#print(tf.get_default_graph().as_graph_def())
with tf.Session() as sess:
    print(sess.run(addition))
sess.close()    

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


### tf.get_variable
    name,
    shape=None,
    dtype=None,
    initializer=None,
    regularizer=None,
    trainable=True,
    collections=None,
    caching_device=None,
    partitioner=None,
    validate_shape=True,
    use_resource=None,
    custom_getter=None,
    constraint=None


In [3]:
tf.reset_default_graph()
#writer = tf.summary.FileWriter("./Graph", tf.get_default_graph)
s = tf.get_variable("scalar", initializer=tf.constant(2)) 
m = tf.get_variable("matrix", initializer=tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable("big_matrix", shape=(784, 10), initializer=tf.zeros_initializer())


In [4]:
with tf.Session() as sess:
    print(sess.run(W.initializer)) #initialize
    print(sess.run(W).shape)
sess.close()

None
(784, 10)


In [5]:
tf.reset_default_graph()
ZX = tf.Variable(1)
print(ZX)
assign_op = ZX.assign(100) #assign operator initializes it for us
with tf.Session() as sess:
    print(sess.run(assign_op))
    print(ZX.eval()) # >> 100
sess.close()

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>
100
100


In [6]:
tf.reset_default_graph()
a = tf.get_variable('scalar', initializer=tf.constant(2)) 
a_times_two = a.assign(a * 2)
with tf.Session() as sess:
    print(sess.run(tf.global_variables_initializer())) 
    print(sess.run(a))
    print(sess.run(a_times_two))
    print(sess.run(a_times_two))
sess.close()

None
2
4
8


In [7]:
a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5,5,5], tf.float32)
c = a+b
writer = tf.summary.FileWriter('graphs/placeholders', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(c,{a:[1,2,3]}))

[6. 7. 8.]
